language: go

sudo: false

matrix:
  include:
    - go: "1.12.x"
      env: GO111MODULE=off
    - go: "1.12.x"
      env: GO111MODULE=on
    - go: "1.13.x"
      env: GO111MODULE=off
    - go: "1.13.x"
      env: GO111MODULE=on
    - go: master
script:
  - gofmt -l .
  - go test -v -race ./test/...
